version: 1

sources:
  - name: raw  # Alias for the dataset (used in dbt references)
    schema: gz_raw_data  # Actual name of the dataset in BigQuery
    tables:
      - name: sales  # Alias for the table in dbt
        identifier: raw_gz_sales  # Actual table name in the database
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship
